### ISSUE TITLE
[FR] After wrapping with a new callout, have title selected

### ISSUE THREAD

**Issue by huyz** [alythobani/obsidian-callout-toggles#10]
After wrapping text in a new callout, instead of having the entire callout selected as it is now, can we have title selected.

That's so that we can quickly either replace, or prepend, or append to the default title.

**Comment by alythobani** [comment]
Hey again @huyz  ! 

I can see this being useful. I'm really short on time these days but can keep this open for eventual implementation (and can be open to PRs if someone wants to implement this themselves).

Do you think you'd prefer this as a setting, e.g.:

**What should be selected after creating a callout?**
* Full callout
* Callout header until cursor
* Callout title

Or as a command, e.g. "Callout Toggles: Select title of current callout" so that you can more easily change its title after the fact?

**Comment by huyz** [comment]
I recommend against a setting. I would just make it the default.  I think other users would be happy with that

**Comment by alythobani** [comment]
I wouldn't assume that ;) I'm one of the users who prefers the current selection behavior, which makes it really easy to switch between callout types (by calling the `Wrap` and `Remove` commands back-to-back).

So if you'd prefer this to be your own default behavior and not implemented as a command, then I'd implement it as a setting, so that everyone can have the functionality that works best for them.

**Comment by alythobani** [comment]
You should be good to go now @huyz ! Version 1.2.0 released, you can now choose `Select callout title` for the first two dropdowns in the new auto-selection settings. (Not available as an option for "After removing a callout" since that wouldn't make as much sense)

Hope it's useful!

**Comment by huyz** [comment]
Great, thanks @alythobani !
