### ISSUE TITLE
[FR] custom callout title

### ISSUE THREAD

**Issue by Flyingfolder** [alythobani/obsidian-callout-toggles#11]
I hope to add a custom callout title.

For example, after setting a callout title in the settings, I can press Ctrl+P in the editor, select the callout I set, and insert the pre-entered callout title from the settings.

(For instance, automatically input "> [!quote]+ First-order Condition" which I have already entered in the settings)

This way, I don't have to type "> [!quote]+ First-order Condition" again and again.

**Comment by alythobani** [comment]
Hey @Tinymacs !

Have you checked out the Callout Manager plugin yet? It could be what you're looking for (and more): you can create a custom callout called `first-order-condition` with the desired icon and color. And then Callout Toggles will provide you a command `Wrap lines in first-order-condition callout` that you can assign a hotkey to if you want.

It wouldn't be the exact same as you're describing under the surface (since the ID would be `first-order-condition` instead of `quote`), but the external behavior would be the same:

<img width="693" alt="Screen Shot 2024-12-12 at 7 57 20 AM" src="https://github.com/user-attachments/assets/4e74213f-2bc2-412c-91c3-d1507f79227f" />

=>

<img width="723" alt="Screen Shot 2024-12-12 at 7 56 19 AM" src="https://github.com/user-attachments/assets/f51a0b2e-ec6b-4483-968f-7187bd178745" />

=>

<img width="789" alt="Screen Shot 2024-12-12 at 7 56 03 AM" src="https://github.com/user-attachments/assets/d46ef247-77b6-4b62-b7b9-1a6fc3f1e853" />

**Comment by Flyingfolder** [comment]
Thanks! (I never thought that these two plug-ins could be used together.)
