### ISSUE TITLE
设置三个快捷键，从光标处执行变换

### ISSUE THREAD

**Issue by qiekqiek** [alythobani/obsidian-callout-toggles#3]
设置三个快捷键，从光标处执行变换，分别是将本句/本行/本区转换格式，降低操作

**Comment by alythobani** [comment]
Hi  @qiekqiek  thanks for the feedback again!

Same message as in #4 - please post in English as I unfortunately am not yet fluent in Chinese (really, I wish I was)!

Here is Google's translation of your feedback:

> Title: Set three shortcut keys to perform transformations from the cursor #3
> Body: Set three shortcut keys to perform transformations from the cursor, namely, convert the format of this sentence/line/area, and reduce the operation

Unfortunately this translation is still not clear. If you're able to elaborate more clearly, and provide some visual examples, that would be helpful. Otherwise I may need to close this issue as well.

Hope you're enjoying the plugin, and have a great day!

**Comment by qiekqiek** [comment]
![2024-11-10_15-54-25](https://github.com/user-attachments/assets/4bad8f58-b3e7-4c33-ac44-f86cca45035a)
like this,dont need to choose all characters

**Comment by alythobani** [comment]
Ah I think I see what you mean. Are you thinking of this plugin providing 3 commands per callout type `X`?

E.g.:
1) `Wrap sentence in X callout`
2) `Wrap line in X callout`
3) `Wrap paragraph in X callout`

**Comment by alythobani** [comment]
Ah, I think I see what you mean. Are you thinking of this plugin providing 3 wrap commands per callout type? E.g. `Wrap sentence in X callout`, `Wrap line in X callout`, and `Wrap paragraph in X callout` for every callout type `X`?

If so, my main concern here would be an overcomplicated user experience, and a cluttered command palette, due to providing too many commands (3x more than we currently do, which is already a lot).

Additionally it should hopefully already be fairly simple to wrap a sentence/line/paragraph as you wish. E.g.:

## Sentence

You just need to put the sentence on its own line before calling `Wrap lines in X callout`:

![sentence](https://github.com/user-attachments/assets/a2f22bd8-f7fb-4ef1-b57e-03ea5e26a2be)


## Line

You just need to have the cursor on the chosen line before calling `Wrap lines in X callout`:

![line](https://github.com/user-attachments/assets/4295b56e-e542-4170-9db3-bcaf1ab1471a)



## Paragraph

You just need to select the paragraph before calling `Wrap lines in X callout`:

![paragraph](https://github.com/user-attachments/assets/7bb21591-9ea4-4d9a-82e7-dc67dc998f2d)

---

So, I'm leaning towards not implementing these extra commands since I'm not sure the benefits would outweigh the increase in complexity and potentially cluttering the command palette with too many commands.

Does this all make sense? Or please let me know if I'm misunderstanding you still!

**Comment by qiekqiek** [comment]
非常好，够用了，谢谢~
